 version: 2
 jobs:
   build:
     docker:
       - image: circleci/openjdk:8-jdk
       
     working_directory: ~/repo

       - run: 
            name: Run tests
            command: mvn clean test
